spring:
  thymeleaf:
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa.show-sql: true
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  jackson:
    serialization.write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    username: labifrs2016.1@gmail.com
    password: software2016
    port: 587
    properties.mail.smtp.starttls.enable: true 