spring:
  thymeleaf:
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa.show-sql: true
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
  jackson:
    serialization.write-dates-as-timestamps: false
